services:
  hfm-api-gateway:
    networks:
      - hfm-user-account-management-service
      - hfm-budget-analysis-service
      - hfm-user-notifications-service
    container_name: hfm_api_gateway
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"

      
networks:
    hfm-user-account-management-service:
        external: true
    hfm-budget-analysis-service:
        external: true
    hfm-user-notifications-service:
        external: true
